blank_issues_enabled: false
contact_links:
  - name: Ask a Question
    url: https://github.com/Khelendrarauniyar/respiroai/discussions
    about: Use GitHub Discussions for questions and community support
