name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install backend dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install -r requirements-minimal.txt
          pip install pytest

      - name: Run backend tests
        working-directory: backend
        run: |
          if [ -d tests ]; then pytest -q || true; else echo "No backend tests"; fi

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci || npm install

      - name: Build frontend
        working-directory: frontend
        run: |
          if [ -f package.json ]; then npm run build --if-present; else echo "No frontend"; fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Python lint (flake8)
        run: |
          pip install flake8 || true
          if [ -d backend ]; then flake8 backend || true; fi

      - name: JS lint (eslint)
        run: |
          if [ -f frontend/package.json ]; then cd frontend && npm install --no-save eslint && npx eslint src || true; fi
